export const DISTRICT_HIERARCHY: Record<string, Record<string, string[]>> = {
  "Alluri Sitharama Raju": {
    "Paderu SDPO": [
      "Dumbriguda",
      "Araku",
      "Anantagiri",
      "Gangaraju Madugula(G.Madugula)",
      "Munchingiput",
      "Pedabayalu",
      "Paderu UPS",
      "Hukumpeta",
    ],
    "Chintapalli SDPO": [
      "Annavaram",
      "Chinthapalli",
      "Gudemkothaveedi (G.K.Veedhi)",
      "Sileru",
      "Koyyuru",
      "Mampa",
    ],
  },
  "Anakapalli": {
    "Anakapalli SDPO": [
      "Chodavaram",
      "Anakapalli Town",
      "Anakapalli Rural",
      "Kasimkota",
      "Anakapalli Traffic",
      "A.Koduru",
      "Cheedikada",
      "Devarapalli",
      "K.Kotapadu",
      "V.Madugula",
      "Butchiyyapeta",
      "Kothakota",
      "Ravikamatham",
      "Rolugunta",
    ],
    "Parawada SDPO": [
      "Yelamanchili Town",
      "Yelamanchili Rural",
      "Rambilli",
      "Munagapaka",
      "Sabbavaram",
      "Parawada",
      "Atchutapuram",
      "Yelamanchili Traffic",
    ],
    "Other": [
      "CCS , Anakapalli",
      "Mahila UPS, Anakapalli",
    ],
    "Narsipatnam SDPO": [
      "Narsipatnam Town",
      "Payakaraopeta",
      "Kotavurtla",
      "Nakkapalli",
      "S.Rayavaram",
      "Golugonda",
      "K.D.Peta",
      "Makavarapalem",
      "Narsipatnam Rural",
      "Nathavaram",
    ],
  },
  "Ananthapuram": {
    "Anantapuram Rural SDPO": [
      "Garladinne",
      "Narpala",
      "Singanamala",
      "Putlur",
      "Yellanur",
      "Anantapur Rural",
      "Bukkaraya Samudram",
      "Atmakur",
      "Itukalapalli",
      "Rapthadu",
    ],
    "Guntakal SDPO": [
      "Guntakal I Town",
      "Guntakal II Town",
      "Uravakonda",
      "Guntakal Rural",
      "Kasapuram",
      "Kuderu UPS",
      "Palthur",
      "Vajrakarur",
      "Vidapanakal",
      "Beluguppa",
      "Gooty",
      "Pamidi",
    ],
    "Kalyanadurg SDPO": [
      "Kalyandurg Town",
      "Rayadurg",
      "Brahamasamudram",
      "Kalyandurg Rural",
      "Kambadur",
      "Kundurpi",
      "Settur",
      "Bommanahal",
      "D.Hirehal",
      "Gummagatta",
      "Kanekal",
    ],
    "Tadipatri SDPO": [
      "Tadipathri Rural",
      "Tadipathri Town",
      "Peddapappur",
      "Peddavadugur",
      "Yadiki",
    ],
    "Other": [
      "Anantapur Traffic",
      "CCS, Anantapur",
      "Mahila UPS, Anantapur",
    ],
    "Anantapuram Town SDPO": [
      "Anantapur I Town",
      "Anantapur II Town",
      "Anantapur III Town",
      "Anantapur IV Town",
    ],
  },
  "Ananthapuramu EXCISE": {
    "Ananthapuramu EXCISE": [
      "Guntakal EXCISE",
      "B.K.Samudram EXCISE",
      "Kalyandurg EXCISE",
      "Kambadur EXCISE",
      "Tadipatri EXCISE",
      "Kanekal EXCISE",
      "Ananthapuramu EXCISE",
      "Gooty EXCISE",
      "Urvakonda EXCISE",
      "Rayadurg EXCISE",
    ],
  },
  "Annamayya": {
    "Madanapalle SDPO": [
      "Peddamandayam",
      "Sodam",
      "Chowdepalli",
      "Punganur UPS",
      "Madanapalle I Town UPS",
      "Madanapalle II Town UPS",
      "Madanapalle Rural UPS",
      "B.Kothakota UPS",
      "Mudiveedu",
      "Nimmanapalle",
      "Ramasamudram",
      "Mulakalacheruvu",
      "P.T.Samudram (PTM)",
      "Somala",
      "Thamballapalli",
    ],
    "Rayachoty SDPO": [
      "Kalikiri UPS",
      "Voyalpad",
      "Sambepalli",
      "Chinnamandem",
      "Piler UPS",
      "Rayachoty Traffic",
      "Rayachoty UPS",
      "Gurramkonda",
      "K.V.Palli",
      "Kalakada",
      "Galiveedu",
      "Lakkireddipalli",
      "Ramapuram",
    ],
  },
  "Annamayya EXCISE": {
    "RAYACHOTY EXCISE": [
      "Rayachoty  EXCISE",
      "Kodur EXCISE",
      "L.R.Palli  EXCISE",
      "Rajampeta EXCISE",
    ],
    "MADANAPALLI EXCISE": [
      "Vayalpad EXCISE",
      "Molakalacheruvu EXCISE",
      "Madanapalli EXCISE",
      "Piler EXCISE",
    ],
  },
  "Bapatla": {
    "Bapatla SDPO": [
      "Bapatla Town UPS",
      "Bapatla Rural UPS",
      "Karlapalem",
      "T. Sandole",
      "Vedullapalli",
      "Martur UPS",
      "Parchur",
      "Yaddanapudi",
    ],
    "Repalle SDPO": [
      "Vemuru",
      "T. Sundur",
      "Kolluru",
      "Bhattiprole",
      "Amruthalur",
      "T. Sodayapalem",
      "Repalle UPS",
      "Adavuladeevi",
      "Cherukupalli",
      "Nagaram",
      "Nizampatnam",
    ],
    "Chirala SDPO": [
      "Chirala I Town UPS",
      "Chirala II Town UPS",
      "Chirala Rural (Epurupalem)",
      "Vetapalem",
      "Chinaganjam",
      "Inkollu",
      "Karamchedu",
    ],
  },
  "Bapatla EXCISE": {
    "Bapatla EXCISE": [
      "Chirala EXCISE",
      "Nagaram EXCISE",
      "Repalle EXCISE",
      "Bapatla EXCISE",
      "Vemuru EXCISE",
      "Parchur EXCISE",
      "Addanki EXCISE",
    ],
  },
  "C I D": {
    "Other": [
      "Cyber Crime",
      "CID Police Station",
    ],
  },
  "Chittoor": {
    "Palamaner SDPO": [
      "V.Kota UPS",
      "Baireddypalle",
      "Gangavaram UPS",
      "Panjani",
      "Bangarupalem UPS",
      "Palamaner UPS",
    ],
    "Kuppam SDPO": [
      "Gudipalli",
      "Rallabudugur",
      "Ramakuppam",
      "Kuppam UPS",
    ],
    "CCS Chittoor Urban SDPO": [
      "CCS Chittoor UPS",
    ],
    "Chittoor Traffic Urban SDPO": [
      "Chittoor Traffic UPS",
    ],
    "Chittoor Mahila Urban SDPO": [
      "Mahila UPS, Chittoor",
    ],
    "Chittoor SDPO": [
      "Chittoor I Town UPS",
      "Chittoor II Town UPS",
      "Chittoor Taluk PS",
      "G.D.Nellore UPS",
      "Narsingarayanipet(N.R.Pet)",
      "Penumur",
      "Gudipala",
      "Kanipakam",
      "Thavanampalle",
      "Yadamari",
      "Irala",
      "Kallur",
      "Puthalapattu UPS",
      "Rompicherla",
    ],
    "Nagari SDPO": [
      "Nagari UPS",
      "K. Nagar",
      "Palasamudram",
      "S.R.Puram",
      "Vedurukuppam",
      "Nindra",
      "Vijayapuram",
    ],
  },
  "Chittoor  EXCISE": {
    "Chittoor  EXCISE": [
      "Kuppam EXCISE",
      "Chittoor Rural EXCISE",
      "Karvetinagaram EXCISE",
      "Punganur EXCISE",
      "Palamaner EXCISE",
      "Pulicherla EXCISE",
      "Chittoor Urban EXCISE",
      "Nagari EXCISE",
    ],
  },
  "Coastal Security Police": {
    "North SDPO": [
      "Antharvedipalem Marine",
      "Vodalarevu Marine",
      "Baruva Marine",
      "Bhavanapadu Marine",
      "Chinthapalli Marine",
      "Kalingapatnam Marine",
      "Pentakota Marine",
      "Port Marine",
      "Pudimadaka Marine",
      "Rushikonda Marine",
      "Vakalapudi Marine",
    ],
    "South SDPO": [
      "Suryalanka Marine",
      "Dugarajapatnam Marine",
      "Gilakaladindi Marine",
      "Isukapalli Marine",
      "Nizampatnam Marine",
      "Orlagonditippa Marine",
      "Palakayatippa Marine",
      "Ramayapatnam Marine",
      "Sriharikota Marine",
      "Kothapatnam Marine",
    ],
  },
  "Dr. B R Ambedkar Konaseema": {
    "Amalapuram SDPO": [
      "Amalapuram Town UPS",
      "Allavaram",
      "Amalapuram Rural",
      "Uppalaguptam",
      "I. Polavaram",
      "Katrenikona",
      "Mummidivaram",
    ],
    "Ramachandrapuram SDPO": [
      "Ramachandrapuram",
      "Pamarru",
      "Draksharama",
    ],
    "Kothapeta SDPO": [
      "Sakhinetipalli",
      "Razole",
      "Ambajipeta",
      "Inavilli",
      "Nagaram",
      "P.Gannavaram",
      "Alamuru",
      "Athreyapuram",
      "Kothapeta",
      "Ravulapalem",
      "Malkipuram",
    ],
  },
  "Dr. B R Ambedkar Konaseema EXCISE": {
    "Amalapuram EXCISE": [
      "Mummidivaram EXCISE",
      "Kothapeta EXCISE",
      "Alamuru EXCISE",
      "Razole EXCISE",
      "Amalapuram EXCISE",
      "Ramachandrapuram EXCISE",
    ],
  },
  "Eagle": {
    "Other": [
      "Narcotics",
    ],
  },
  "East Godavari": {
    "East Zone": [
      "Rangampeta",
      "Mandapeta Town UPS",
      "Angara",
      "Mandapeta Rural",
      "Rayavaram",
      "Anaparthi",
      "Biccavole",
    ],
    "South Zone": [
      "Kadiam UPS",
      "Dowaleswaram UPS",
      "Bommuru UPS",
      "Rajahmundry II Town UPS",
    ],
    "Rajahmundry Crimes": [
      "CCS - IV",
      "CCS - III",
      "CCS - II",
      "CCS - I",
    ],
    "North Zone": [
      "Seethanagaram",
      "Rajanagaram UPS",
      "Airport PS",
      "Gokavaram",
      "Korukonda",
    ],
    "Other": [
      "Mahila UPS, East Godavari",
      "Traffic UPS, East Godavari",
    ],
    "Central Zone": [
      "Prakash Nagar UPS",
      "Rajahmundry I Town UPS",
      "Rajahmundry III Town UPS",
    ],
    "Kovvur SDPO": [
      "Kovvur Town",
      "Nallajerla UPS",
      "Devarapalli",
      "Gopalapuram",
      "Chagallu",
      "Kovvur Rural",
      "Tallapudi",
      "Nidadavole Town",
      "Peravalli",
      "Samisrigudem",
      "Undrajavaram",
    ],
  },
  "East Godavari EXCISE": {
    "EAST GODAVARI EXCISE": [
      "Rajamahendravaram (North) EXCISE",
      "Rangampeta EXCISE",
      "Nidadavolu EXCISE",
      "Devarapalli EXCISE",
      "Kovvuru EXCISE",
      "Korukonda EXCISE",
      "Rajamahendravaram (South) EXCISE",
    ],
  },
  "Eluru": {
    "Nuzvid SDPO": [
      "Denduluru",
      "Pedavegi",
      "Pedapadu",
      "Nuzvid Town",
      "Agiripalli",
      "Chatrai",
      "Musunuru",
      "Nuzvid Rural",
    ],
    "Polavaram SDPO": [
      "Buttaigudem",
      "Jeelugumilli",
      "T.Narasapuram",
      "Kukunoor",
      "Velerupadu",
      "Koyyalagudem",
      "Polavaram",
    ],
    "Other": [
      "CCS , Eluru",
      "Mahila UPS, Eluru",
      "Eluru Traffic",
    ],
    "Eluru SDPO": [
      "Eluru I Town",
      "Eluru II Town",
      "Eluru III Town",
      "Kaikaluru Town",
      "Bhimadole",
      "Dwaraka Tirumala",
      "Eluru Rural",
      "Chebrole",
      "Ganapavaram",
      "Nidamarru",
      "Kaikaluru Rural",
      "Kalidindi",
      "Mandavalli",
      "Mudinepalli",
    ],
    "Jangareddygudem SDPO": [
      "Chintalapudi",
      "Dharmajigudem",
      "Jangareddygudem",
      "Jangareddygudem Traffic",
      "Lakkavaram",
      "Tadikalapudi",
    ],
  },
  "GRP Guntakal": {
    "Tirupati SDPO": [
      "Chittoor",
      "Renigunta",
      "Thirupathi",
      "Kadapa",
      "Yerraguntla",
    ],
    "Guntakal SDPO": [
      "Anantapur",
      "Dharmavaram",
      "Hindupur",
      "Kadiri",
      "Adoni",
      "Gooty",
      "Guntakal",
      "Kurnool",
      "Nandyal",
    ],
    "Nellore SDPO": [
      "Gudur",
      "Kavali",
      "Nellore",
      "Chirala",
      "Ongole",
    ],
  },
  "GRP Vijayawada": {
    "VIsakhapatnam RP SDPO": [
      "Vizianagaram",
      "Visakhapatnam",
      "Palasa",
    ],
    "Rajahmundry RP SDPO": [
      "Tuni",
      "Rajahmundry",
      "Bhimavaram",
      "Tadepalligudem",
      "Samalkot",
    ],
    "VIjayawada RP SDPO": [
      "Gudiwada",
      "Eluru",
      "Vijayawada",
    ],
    "Guntur RP SDPO": [
      "Guntur",
      "Nadikudi",
      "Narasaraopet",
      "Tenali",
    ],
  },
  "Guntur": {
    "East Sub Division": [
      "Old guntur",
      "Kothapet",
      "Lalapet",
    ],
    "West Sub Division": [
      "Nagarampalem",
      "Arundalpet",
      "Pattabhipuram",
    ],
    "Thulluru SDPO": [
      "Phirangipuram PS",
      "Thulluru",
      "Thulluru Traffic",
      "Medikonduru",
      "Tadikonda",
    ],
    "Other": [
      "CCS , Guntur",
      "Mahila UPS, Guntur",
      "Guntur Traffic",
    ],
    "North Sub Division": [
      "Mangalagiri Town",
      "Pedakakani",
      "Tadepalli",
      "Duggirala",
      "Mangalagiri Rural",
    ],
    "South Sub Division": [
      "Nallapadu",
      "Kakumanu",
      "Pedanandipadu",
      "Prathipadu",
      "Vatticherukuru",
    ],
    "Tenali SDPO": [
      "Ponnur Town",
      "Tenali I Town",
      "Tenali II Town",
      "Tenali III Town",
      "Chebrolu",
      "Ponnur Rural",
      "Kollipara",
      "Tenali Rural",
    ],
  },
  "Intelligence  Unit": {
    "IGP Int": [
      "CI Cell PS",
    ],
  },
  "Kakinada": {
    "Kakinada Crimes": [
      "Kakinada CCS",
      "Kakinada I Town CCS",
      "Kakinada II Town CCS",
      "Kakinada III Town CCS",
    ],
    "Peddapuram SDPO": [
      "Rowthulapudi",
      "Samalkot",
      "Tuni Town",
      "Gandepalli",
      "Jaggampeta",
      "Kirlampudi",
      "Peddapuram",
      "Annavaram",
      "Yeleswaram",
      "Prathipadu",
      "Kotananduru",
      "Thondangi",
      "Tuni Rural",
    ],
    "Other": [
      "Mahila UPS, Kakinada",
      "Kakinada Traffic I",
      "Kakinada Traffic II",
    ],
    "Kakinada SDPO": [
      "Kakinada I Town",
      "Kakinada II Town",
      "Kakinada III Town",
      "Kakinada Port",
      "Sarpavaram",
      "Coringa",
      "Gollapalem",
      "Indrapalem",
      "Karapa",
      "Pedapudi",
      "Thimmapuram",
      "Gollaprole",
      "Pithapuram Rural",
      "Pithapuram Town",
      "U. Kothapalli",
    ],
  },
  "Krishna": {
    "Avanigadda SDPO": [
      "Challapalli",
      "Avanigadda",
      "Koduru",
      "Nagayalanka",
      "Ghantasala",
    ],
    "Gudivada SDPO": [
      "Gudivada II Town UPS",
      "Gudivada I Town UPS",
      "Gudivada Rural",
      "Gudlavalleru",
      "Nandivada",
      "Kuchipudi",
      "Pamarru",
      "Pedaparupudi",
      "Pamidimukkala",
      "Thotlavalluru",
      "Gudivada Traffic",
    ],
    "Gannavaram SDPO": [
      "Vuyyuru Rural",
      "Kankipadu",
      "Veeravalli",
      "Hanuman Junction",
      "Atkuru",
      "Gannavaram Traffic UPS",
      "Gannavaram UPS",
      "Penamaluru UPS",
      "Vuyyuru Town UPS",
      "Unguturu",
    ],
    "Other": [
      "Bandar Traffic",
      "CCS UPS, Gudivada",
      "CCS UPS, Machilipatnam",
      "Mahila UPS, Machilipatnam",
    ],
    "Bandar SDPO": [
      "Chilakalapudi UPS",
      "Inaguduru UPS",
      "Robertsonpet",
      "Bantumilli",
      "Guduru",
      "Kruthivennu",
      "Pedana",
      "Bandar Taluk PS",
      "Machilipatnam Town",
    ],
  },
  "Kurnool": {
    "Adoni SDPO": [
      "Adoni I Town",
      "Adoni II Town",
      "Adoni III Town",
      "Adoni Traffic",
      "Adoni Rural",
      "Isvi",
      "Peddathumbalam",
    ],
    "Yemmiganur SDPO": [
      "Nandavaram",
      "Yemmiganur Traffic",
      "Yemmiganur Rural",
      "Yemmiganur Town",
      "Kosigi",
      "Kowthalam",
      "Peddakadubur",
      "Madhavaram",
      "Manthralayam",
      "Gonegandla",
    ],
    "Other": [
      "Mahila UPS, Kurnool",
      "CCS , Kurnool",
      "Kurnool Traffic",
    ],
    "Kurnool SDPO": [
      "Kurnool I Town",
      "Kurnool II Town",
      "Kurnool III Town",
      "Kurnool IV Town",
      "Kurnool Taluk",
      "C.Belgal",
      "Gudur",
      "Kodumur",
      "K.Nagalapuram",
      "Oravakal",
      "Ulindakonda",
    ],
    "Pathikonda SDPO": [
      "Pathikonda",
      "Alur",
      "Aspari",
      "Chippagiri",
      "Halaharvi",
      "Holagunda",
      "Devanakonda",
      "Jonnagiri",
      "Maddikera",
      "Tuggali",
      "Krishnagiri",
      "Veldurthi",
    ],
  },
  "Markapuram": {
    "Markapuram SDPO": [
      "Tripuranthakam",
      "Ardhaveedu",
      "Besthavaripeta",
      "Cumbum",
      "Giddalur UPS",
      "Komarolu",
      "Racherla",
      "Markapur Rural",
      "Markapur Town",
      "Dornala",
      "Peddaraveedu",
      "Pullala Cheruvu",
      "Yerragondapalem",
    ],
    "Kanigiri SDPO": [
      "Tarlupadu (Tadivaripalli)",
      "Kanigiri",
      "Peddacherlopalli",
      "C.S.Puram",
      "Pamur",
      "Veligandla",
      "Konakanamitla",
      "Podili",
      "Hanumanthunipadu",
    ],
  },
  "NTR Commissionerate": {
    "Other": [
      "Krishnalanka-CRIME",
      "Machavaram-CRIME",
      "Patamata-CRIME",
      "Vijayawada I Tn-CRIME",
      "Vijayawada II Town-CRIME",
      "Governorpet-CRIME",
      "Suryaraopet-CRIME",
      "Satyanarayanapuram-CRIME",
    ],
    "DCP Crimes": [
      "CCS , Vijayawada",
      "Cyber Crime",
    ],
    "DCP LO-1": [
      "Mahila UPS, Vijayawada",
      "Gunadala",
      "Machavaram",
      "Patamata",
      "Governorpet",
      "Krishnalanka",
      "Suryaraopet",
    ],
    "DCP LO-2": [
      "Ajith Singh Nagar",
      "Nunna",
      "Satyanarayanapuram",
      "Bhavanipuram",
      "Ibrahimpatnam",
      "Vijayawada I Town",
      "Vijayawada II Town",
    ],
    "DCP Traffic": [
      "Vijayawada Traffic I (T)",
      "Vijayawada Traffic II (T)",
      "Vijayawada Traffic III (T)",
      "Vijayawada Traffic IV (T)",
      "Vijayawada Traffic V (T)",
    ],
    "Mylavaram SDPO": [
      "G. Konduru",
      "Mylavaram",
      "Reddigudem",
      "A. Konduru",
      "Gampalagudem",
      "Tiruvuru",
      "Vissannapet",
    ],
    "Nandigama SDPO": [
      "Nandigama",
      "Chillakallu",
      "Jaggaiahpet",
      "Penuganchiprolu",
      "Vatsavai",
      "Chandarlapadu",
      "Kanchikacherla",
      "Veerulapadu",
    ],
  },
  "Nandyal": {
    "Allagadda SDPO": [
      "Allagadda Town",
      "Allagadda Rural",
      "Chagalamarri",
      "Dornipadu",
      "Uyyalawada",
      "Koilakuntla",
      "Kolimigundla",
      "Revanur",
      "Sanjamala",
      "Rudravaram",
      "Sirivella",
    ],
    "Nandyal SDPO": [
      "Panyam",
      "Gadivemula",
      "Mahanandi",
      "Gospadu",
      "B.Atmakur",
      "Nandyal Traffic",
      "Nandyal Taluk",
      "Nandyal III Town",
      "Nandyal II Town",
      "Nandyal I Town",
    ],
    "Dhone SDPO": [
      "Peapully",
      "N.Racherla",
      "Jaladurgam",
      "Owk",
      "Nandivargam",
      "Banaganapalli",
      "Dhone Town",
      "Bethamcherla",
      "Dhone Rural",
    ],
    "Atmakur SDPO": [
      "Nandikotkur",
      "Atmakur",
      "Kothapalli",
      "Pamulapadu",
      "Velugodu",
      "Brahamanakotkur",
      "Jupadu Bangalow",
      "Midthur",
      "Muchumarri",
      "Srisailam I Town",
      "Srisailam II Town",
    ],
  },
  "Palnadu": {
    "Narsaraopet SDPO": [
      "Narasaraopet Rural",
      "Rompicherla",
      "Bandlamotu",
      "Inavole",
      "Ipur",
      "Savalyapuram",
      "Chilakaluripet Town",
      "Narsaraopet I Town",
      "Narsaraopet II Town",
      "Vinukonda",
      "Chilakaluripet Rural",
      "Edlapadu",
      "Nadendla",
      "Narasaraopet Trafic PS",
    ],
    "Sattenapalli SDPO": [
      "Amaravathi",
      "Sattenapalli Town",
      "Atchampet",
      "Bellamkonda",
      "Krosuru",
      "Pedakurapadu",
      "Muppalla",
      "Nekarekal",
      "Rajupalem",
      "Sattenapalli Rural",
    ],
    "Other": [
      "CCS , Palnadu",
      "Mahila UPS, Palnadu",
    ],
    "Gurazala SDPO": [
      "Dachepalli",
      "Gurazala Town",
      "Macherla Town",
      "Piduguralla",
      "Machavaram",
      "Durgi",
      "Karempudi",
      "Rentachinthala",
      "Macherla Rural",
      "Nagarjunasagar",
      "Veldurthy",
    ],
  },
  "Parvathipuram Manyam": {
    "Palakonda SDPO": [
      "Palakonda",
      "Chinamerangi",
      "Garugubilli",
      "Jiyyammavalasa",
      "Elwinpeta",
      "Kurupam",
      "Neelakantapuram",
      "Bathili",
      "Donubhai",
      "Seethampeta",
      "Veeraghattam",
    ],
    "Parvathipuram SDPO": [
      "Pachipenta",
      "Makkuva",
      "Parvathipuram Traffic",
      "Seethanagaram",
      "Salur Rural",
      "Kotiya",
      "Parvathipuram Town",
      "Salur Town",
      "Balijipeta",
      "Komarada",
      "Parvathipuram Rural",
    ],
  },
  "Polavaram": {
    "Chinturu SDPO": [
      "Chintoor",
      "Moothugudem",
      "Kunavaram",
      "Vara Ramachandrapuram",
      "Yetapaka",
      "Donkarai",
    ],
    "Rampachodavaram SDPO": [
      "Rampachodavaram",
      "Addateegala",
      "Dutcherthi",
      "Gangavaram",
      "Y. Ramavaram",
      "Gurthedu",
      "Maredumilli",
      "Jaddangi",
      "Rajavommangi",
      "Devipatnam",
    ],
  },
  "Prakasam": {
    "Kandukur SDPO": [
      "Kandukuru Rural",
      "Voletivaripalem",
      "Lingasamudram",
      "Gudlur",
      "Ulavapadu",
      "Kondepi",
      "Marripudi",
      "Ponnalur",
      "Kandukur Town",
    ],
    "Ongole SDPO": [
      "Naguluppalapadu (N.G. Padu)",
      "Tangutur",
      "Singarayakonda",
      "Jarugumalli",
      "Santhanuthalapadu",
      "Ongole I Town UPS",
      "Ongole II Town UPS",
      "Ongole Taluk UPS",
      "Kothapatnam",
      "Chimakurthy UPS",
      "Maddipadu",
    ],
    "Darsi SDPO": [
      "Donakonda",
      "Ballikurava",
      "Santhamagulur",
      "Addanki UPS",
      "J.Pangulur",
      "Korisapadu",
      "Medarametla",
      "Darsi",
      "Mundlamur",
      "Thallur",
      "Kurichedu",
    ],
    "Other": [
      "CCS , Ongole",
      "Mahila UPS, Ongole",
      "Traffic , Ongole",
    ],
  },
  "Red Sanders Anti-Smuggling Task Force": {
    "Other": [
      "Red Sander Anti smuggling task force",
    ],
  },
  "Sri Potti Sriramulu Nellore": {
    "Kavali SDPO": [
      "Dagadarthi",
      "Bitragunta",
      "Duttaluru",
      "S.R.Puram",
      "Udayagiri",
      "Varikunta Padu",
      "Kavali I Town UPS",
      "Kavali II Town UPS",
      "Jaladanki",
      "Kaligiri",
      "Kondapuram",
      "Vinjamur",
      "Allur",
      "Kavali Rural UPS",
    ],
    "Nellore Rural SDPO": [
      "Nellore Rural UPS",
      "Buchireddypalem UPS",
      "Kodavalur",
      "Vidavalur",
      "Indukurpet",
      "Kovur",
      "Krishnapatnam Port",
      "Muttukur",
      "Totapalli Gudur",
      "V. Sataram UPS",
      "Manubolu",
      "Podalakur",
    ],
    "Atmakur SDPO": [
      "Chejerla",
      "A.S.Pet",
      "Ananthasagaram",
      "Atmakur",
      "Marripadu (D.C.Palli)",
      "Sangam",
      "Somasila",
      "Kaluvoy",
      "Kandaleru",
      "Rapur",
      "Sydapuram",
    ],
    "Nellore Town SDPO": [
      "Balajinagar UPS",
      "Chinna Bazar UPS",
      "Dargamitta UPS",
      "Nawabpet UPS",
      "Santhapet UPS",
      "Vedayapalem UPS",
    ],
    "Gudur SDPO": [
      "Gudur I Town UPS",
      "Gudur II Town UPS",
      "Chillakur",
      "Gudur Rural",
      "Kota",
    ],
    "Other": [
      "CCS , Nellore",
      "Mahila UPS, Nellore",
      "North Traffic, Nellore",
      "South Traffic, Nellore",
    ],
  },
  "Sri Sathya Sai": {
    "Puttaparthi SDPO": [
      "Bukkapatnam",
      "kothacheruvu ups",
      "Puttaparthy Rural",
      "Puttaparthi Town",
      "Puttaparthi Airport",
      "Puttaparthi Security Wing",
      "Amadaguru",
      "Nallamada",
      "O.D.Cheruvu",
    ],
    "Dharmavaram SDPO": [
      "Dharmavaram II Town",
      "Dharmavaram I Town",
      "Bathalapalli",
      "Mudigubba",
      "Patnam",
      "Dharmavaram Rural",
      "Tadimarri",
      "Chennekothapalli",
      "Kanaganapalli",
      "Ramagiri",
    ],
    "Hindupur SDPO": [
      "Hindupur I Town",
      "Hindupur II Town",
      "Hindupur Rural",
      "Chilmathur",
      "Hindupuram Traffic",
      "Lepakshi",
    ],
    "Kadiri SDPO": [
      "Kadiri Rural",
      "Kadiri Town",
      "Gandlapenta",
      "N.P.Kunta",
      "Nallacheruvu",
      "Talupula",
      "Tanakal",
    ],
    "Penukonda SDPO": [
      "Gorantla",
      "Agali",
      "Amarapuram",
      "Gudibanda",
      "Madakasira ups",
      "Rolla",
      "KIA PS",
      "Parigi",
      "Penukonda",
      "Roddam",
      "Somandepalli",
    ],
  },
  "Srikakulam": {
    "Kasibugga SDPO": [
      "Vajrapukothuru",
      "Kasibugga",
      "Itchapuram Rural",
      "Itchapuram Town",
      "Kaviti",
      "Mandasa",
      "Baruva",
      "Kanchili",
      "Sompeta",
    ],
    "Tekkali SDPO": [
      "Santhabommali",
      "Naupada",
      "Nandigam",
      "Kotabommali",
      "Pathapatnam",
      "Meliaputti",
      "Saravakota",
      "Polaki",
      "Narasannapeta",
      "Jalumuru",
      "Kothuru",
      "Tekkali PS",
      "Hiramandalam",
    ],
    "Other": [
      "CCS , Srikakulam",
      "Mahila UPS, Srikakulam",
      "Srikakulam Traffic",
    ],
    "Srikakulam SDPO": [
      "Srikakulam II Town",
      "Amadalavalasa",
      "Burja",
      "Ponduru",
      "Sarubujjili",
      "Etcherla",
      "G. Sigadam",
      "J.R.Puram",
      "Laveru",
      "Gara",
      "Srikakulam I Town",
      "Srikakulam Rural",
    ],
  },
  "Tirupathi": {
    "Other": [
      "CCS , Tirumala",
      "CCS , Tirupathi",
      "Mahila UPS, Tirupathi",
      "Tirumala Traffic",
      "Tirupathi Traffic",
    ],
    "Naidupet SDPO": [
      "Naidupet UPS",
      "Doravari Satram",
      "Ozili",
      "Pellakur",
      "Sriharikota",
      "Sullurpet",
      "Tada",
      "Chittamuru",
      "Vakadu",
      "Balayapalli",
      "Dakkili",
      "Venkatagiri",
    ],
    "Puttur SDPO": [
      "Puttur UPS",
      "Vadamalpet",
      "K.V.B.Puram",
      "Narayanavanam",
      "Pitchatoor",
      "Nagalapuram",
      "Satyavedu",
      "Vardaiahpalem",
    ],
    "Renigunta SDPO": [
      "Renigunta UPS",
      "Yerpedu UPS",
      "Airport",
      "Gajula mandyam",
      "Chitvel",
      "Railway Kodur UPS",
      "Obulavaripalli",
      "Penagalur",
      "Pullampeta",
    ],
    "Sri City SDPO": [
      "Sri City UPS",
    ],
    "Srikalahasti SDPO": [
      "Srikalahasthi I Town UPS",
      "Srikalahasti II Town UPS",
      "Srikalahasthi Rural UPS",
      "B.N.Kandriga",
      "Thottambedu",
    ],
    "Tirumala SDPO": [
      "Tirumala I Town UPS",
      "Tirumala II Town UPS",
    ],
    "Tirupati SDPO": [
      "Alipiri UPS",
      "Tirupathi East UPS",
      "S.V.U.Campus UPS",
      "Tirupathi West UPS",
    ],
    "Chandragiri SDPO": [
      "Tirchanur UPS",
      "Chandragiri UPS",
      "Tirupati Rural UPS",
      "Pakala UPS",
      "Bhakarapet",
      "Yerravaripalem",
      "RC Puram",
    ],
  },
  "Visakhapatnam Commissionerate": {
    "DCP L&O-I": [
      "Muvvalavanipalem",
      "Arilova",
      "Dwaraka",
      "II Town",
      "III Town",
      "IV Town",
      "Maharanipeta",
      "Anandapuram",
      "Bhimunipatnam",
      "Padmanabham",
      "PM Palem",
    ],
    "DCP L&O-II": [
      "Kancharapalem PS",
      "Gopalapatnam",
      "Airport",
      "Steelplant",
      "Gajuwaka",
      "Pendurthy",
      "Harbour",
      "I Town",
      "Malkapuram",
      "New Port",
      "Duvvada",
    ],
    "Other": [
      "Mahila UPS, Visakhapatnam",
    ],
    "ADCP, Traffic": [
      "Gajuwaka Traffic",
      "I Town Traffic",
      "II Town Traffic",
      "III Town Traffic",
      "IV Town Traffic",
      "Kancharapalem Traffic",
      "New Port Traffic",
    ],
    "DCP Crime": [
      "CCS",
      "Cyber Crime",
    ],
  },
  "Vizianagaram": {
    "Vizianagaram SDPO": [
      "Gantyada",
      "Vizianagaram Rural",
      "Kothavalasa",
      "Vizianagaram I Town",
      "Vizianagaram II Town",
      "Bhogapuram",
      "Denkada",
      "Nellimarla",
      "Pusapatirega",
      "Jami",
      "L Kota",
      "S.Kota",
      "Vallampudi",
    ],
    "Other": [
      "CCS , Vizianagaram",
      "Mahila UPS, Vizianagaram",
      "Vizianagaram Traffic",
    ],
    "Bobbili SDPO": [
      "Bobbili Town",
      "Badangi",
      "Ramabhadrapuram",
      "Therlam",
      "Bobbili Traffic",
      "Andra",
      "Burjavalasa",
      "Bondapalli",
      "Gajapathinagaram",
      "Pedamanapuram",
    ],
    "Cheepurupalli SDPO": [
      "Rajam Town",
      "Budarayavalasa",
      "Cheepurupalli",
      "Garividi",
      "Gurla",
      "Regidi Amudalavalsa",
      "Santhakaviti",
      "Vangara",
    ],
  },
  "West Godavari": {
    "Bhimavaram SDPO": [
      "Bhimavaram Traffic",
      "Bhimavaram I Town",
      "Bhimavaram II Town",
      "Akividu",
      "Kalla",
      "Undi",
      "Bhimavaram Rural",
      "Palakoderu",
      "Veeravasaram",
    ],
    "Tadepalligudem SDPO": [
      "Tanuku Traffic PS",
      "Tanuku Rural",
      "Iragavaram",
      "Attili",
      "Tadepalligudem Town",
      "Pentapadu",
      "Tadepalligudem Rural",
      "Tadepalligudem Traffic",
      "Tanuku Town",
    ],
    "Narasapuram SDPO": [
      "Penumantra",
      "Narasapuram Town",
      "Palakollu Town",
      "Mogaltur",
      "Narasapuram Rural",
      "Palakollu Rural",
      "Poduru",
      "Yelamanchili",
      "Achanta",
      "Penugonda",
    ],
  },
  "YSR Kadapa": {
    "Kadapa SDPO": [
      "CCS  , Kadapa",
      "Kadapa Traffic UPS",
      "Chinna Chowk UPS",
      "Kadapa I Town UPS",
      "Kadapa II Town UPS",
      "Kadapa Rural UPS",
      "RIMS UPS",
      "Chintakomma Dinne UPS",
      "Pendlimarri",
      "Vallur",
      "Chennur UPS",
      "Gangireddipalli (V.N.Palli)",
      "Kamalapuram",
    ],
    "Rajampet SDPO": [
      "Veeraballi",
      "Sidhout",
      "Vontimitta",
      "Rajampet UPS",
      "Mannur UPS",
      "Nandalur",
      "T. Sundupalli",
    ],
    "Jammalamadugu SDPO": [
      "Jammalamadugu UPS",
      "Muddanur UPS",
      "Yerraguntla UPS",
      "Mylavaram",
      "Peddamudium",
      "Talamanchipatnam",
      "Kalamalla",
      "Kondapuram",
      "Tallaproddatur",
    ],
    "Mydukur SDPO": [
      "Badvel UPS",
      "Mydukur UPS",
      "Atlur",
      "B.Kodur",
      "Badvel Rural (Gopavaram)",
      "B.Matam",
      "Chapadu",
      "Duvvur",
      "Khajipet UPS",
      "Kalasapadu",
      "Porumamilla",
      "S.A.Kasinayana (SAKN PS)",
    ],
    "Proddatur SDPO": [
      "Proddatur I Town UPS",
      "Proddatur II Town UPS",
      "Proddatur III Town UPS",
      "Proddatur Traffic",
      "Proddatur Rural",
      "Rajupalem",
    ],
    "Pulivendula SDPO": [
      "Pulivendula Traffic",
      "Pulivendula UPS",
      "Vempalli UPS",
      "Lingala",
      "Simhadripuram",
      "Thondur",
      "Chekrayapet",
      "RK Valley",
      "Vemula",
    ],
    "Other": [
      "Mahila UPS, Kadapa",
    ],
  },
  "Prism": {
    "North SDPO": [
      "Prism North Town PS",
      "Prism North Traffic PS",
      "Prism North Rural PS",
    ],
    "South SDPO": [
      "Prism South Town PS",
      "Prism South Traffic PS",
      "Prism South Rural PS",
    ],
    "East SDPO": [
      "Prism East Town PS",
      "Prism East Traffic PS",
      "Prism East Rural PS",
    ],
    "West SDPO": [
      "Prism West Town PS",
      "Prism West Traffic PS",
      "Prism West Rural PS",
    ],
    "Centre SDPO": [
      "Prism Centre Town PS",
      "Prism Centre Traffic PS",
      "Prism Centre Control Room PS",
    ],
    "Mahila SDPO": [
      "Prism Mahila PS",
      "Prism Women Support PS",
      "Prism SHE Team PS",
    ],
  },
};
